return {
  "nvim-treesitter/nvim-treesitter",
  highlight = { enable = true },
  indent = { enable = true },
  opts = {
    ensure_installed = {
      "angular",
      "c_sharp",
      "bash",
      "html",
      "http",
      "javascript",
      "json",
      "jsonc",
      "lua",
      "markdown",
      "markdown_inline",
      "query",
      "regex",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "sql",
      "scss",
      "css",
      "xml",
      "dockerfile",
      "dot",
      "cpp",
      "nix",
      "graphql",
      "vimdoc",
    },
  },
}
